# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serving.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rserving.proto\x12\x12tensorslow.serving\"$\n\x06Matrix\x12\r\n\x05value\x18\x01 \x03(\x02\x12\x0b\n\x03\x64im\x18\x02 \x03(\x05\"6\n\nPredictReq\x12(\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1a.tensorslow.serving.Matrix\"7\n\x0bPredictResp\x12(\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1a.tensorslow.serving.Matrix2a\n\x11TensorSlowServing\x12L\n\x07Predict\x12\x1e.tensorslow.serving.PredictReq\x1a\x1f.tensorslow.serving.PredictResp\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serving_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MATRIX._serialized_start=37
  _MATRIX._serialized_end=73
  _PREDICTREQ._serialized_start=75
  _PREDICTREQ._serialized_end=129
  _PREDICTRESP._serialized_start=131
  _PREDICTRESP._serialized_end=186
  _TENSORSLOWSERVING._serialized_start=188
  _TENSORSLOWSERVING._serialized_end=285
# @@protoc_insertion_point(module_scope)
